logging.level.org.springframework=INFO
server.port = 8080
###Things####
spring.Datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/teacherapp?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
spring.Datasource.username=root
spring.datasource.password=Password
## Hibernate configuration ##

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.application.name=demo
